### ISSUE TITLE
US: As a user, I want to choose the delivery time slot, so that I can get access the list of restaurants

### ISSUE THREAD

**Issue by neoteristis** [PNS-Conception/ste-23-24-equipe-c#25]
### Difficulty

M ⚠️

### Priority

1000 (Must Have)

### Business Rules

The user can choose a delivery time slot. Choosing a delivery time slot is mandatory before accessing the list of restaurants. The user can only choose from the provided delivery time slots. The list of restaurants is accessible once a delivery time slot is selected.

### Acceptance Criteria

- [ ] The user can have access to the list of delivery time slots. // not needed
- [x] The user can choose one delivery time slot.
- [ ] The user can't access the list of restaurants if they have not chosen a delivery time slot. // not needed
- [ ] The user can only choose a delivery time slot from the provided list. // no list provided

### Acceptance Scenarios

// There is no list of available delivery time slots
- [ ] Scenario 1: The user can have access to the list of delivery time slots
    - Given: A user
    - When: The user starts the process of creating an order
    - Then: The user should have access to the list of delivery time slots

// A non logged in user have access
- [ ] Scenario 2: The user can choose one delivery time slot
    - Given: A user
    - And: The user has accessed the list of delivery time slots
    - When: The user chooses one delivery time slot
    - And: Chooses to continue the process
    - Then: The user is sent to the list of restaurants

- [ ] Scenario 3: The user can't access the list of restaurants if they have not chosen a delivery time slot
    - Given: A user
    - And: The user has accessed the list of delivery time slots
    - And: The user has not chosen a delivery time slot
    - When: The user tries to access the list of restaurants
    - Then: The user is not authorized

// There is no list of available delivery time slots
- [ ] Scenario 4: The user can only choose a delivery time slot from the provided list
    - Given: A user
    - When: The user gets access to the list of delivery time slots
    - Then: The user can only choose one from the provided time slots
Branches:
- [x] #41
- [x] #45
- [x] #47
- [x] #49

**Comment by ozeliurs** [comment]
Acceptance criteria completed.
